'use client';
import {useState} from 'react';

type Media={title:string;source:string;url:string;contentType:string;size:number;formats:{mp3:string[];mp4:string[]}};
const Icon=({children}:{children:React.ReactNode})=><span style={{display:'inline-flex',width:18,height:18,alignItems:'center',justifyContent:'center'}}>{children}</span>;
function Play(){return <Icon><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M8 5v14l11-7z"/></svg></Icon>}
function LinkIcon(){return <Icon><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1"/><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2a5 5 0 0 0 7.1 7.1l1.1-1.1"/></svg></Icon>}
export default function Home(){
 const [url,setUrl]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [media,setMedia]=useState<Media|null>(null); const [format,setFormat]=useState<'mp3'|'mp4'>('mp4'); const [quality,setQuality]=useState('720p'); const [playing,setPlaying]=useState(false); const [downloading,setDownloading]=useState(false);
 async function process(){setError('');setMedia(null);setLoading(true);try{const r=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.error||d.message||'Unable to process URL');if(!d.supported)throw new Error(d.message);setMedia(d.media);const first = d.media.formats.mp4.length ? 'mp4' : 'mp3'; setFormat(first); setQuality(first==='mp4'?'720p':'128kbps')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function download(){if(!media)return;setDownloading(true);try{const r=await fetch('/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceUrl:media.url,format,quality})});if(!r.ok){const d=await r.json();throw new Error(d.error||'Download failed')}const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${media.title}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e:any){setError(e.message)}finally{setDownloading(false)}}
 return <main className="wrap"><header className="top"><div className="logo">MediaFlow</div><div className="pill">Fast • Private by design</div></header><section className="hero"><h1>Download Video &amp; Audio</h1><p>Paste a direct public media link, preview it, choose MP3 or MP4 quality, and download.</p><div className="box process"><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&process()} placeholder="Paste direct video or audio link here…"/><button className="btn" disabled={!url||loading} onClick={process}><LinkIcon/> {loading?'Processing…':'Process'}</button></div></section><div className="ad">Advertisement</div>{error&&<div className="notice">{error}</div>}{media&&<section className="box result"><div className="meta"><div className="thumb"><Play/></div><div><div className="title">{media.title}</div><div className="muted">{media.source} · {media.contentType}</div></div></div><div className="preview">{format==='mp4'?<video controls autoPlay={playing} src={media.url} onPlay={()=>setPlaying(true)}/>:<audio controls autoPlay={playing} src={media.url} onPlay={()=>setPlaying(true)}/>}</div><div className="actions">{media.formats.mp3.length>0&&<button className={`format ${format==='mp3'?'active':''}`} onClick={()=>{setFormat('mp3');setQuality('128kbps')}}><strong>MP3</strong><span className="muted">Audio</span></button>} {media.formats.mp4.length>0&&<button className={`format ${format==='mp4'?'active':''}`} onClick={()=>{setFormat('mp4');setQuality('720p')}}><strong>MP4</strong><span className="muted">Video</span></button>} </div><div className="qualities">{media.formats[format].map(q=><button key={q} className={`quality ${quality===q?'active':''}`} onClick={()=>setQuality(q)}>{q}</button>)}</div><button className="btn download" onClick={download} disabled={downloading}>{downloading?'Preparing file…':`Download ${format.toUpperCase()} · ${quality}`}</button></section>}<div className="ad">Advertisement</div><footer className="footer">Only download content you own or have permission to use. No DRM or private-content bypassing.</footer></main>
}
